version: '3.9'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=web-server
      - MONGO_INITDB_ROOT_PASSWORD=web-server
      - MONGO_INITDB_DATABASE=licencias
  networks:
    - mean-licencias
  
networks:
  mean-licencias: